# Generated by Django 6.0.1 on 2026-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('PL', 'PLAIN'), ('KL', 'KIWI'), ('EL', 'ELAICHI'), ('GR', 'GINGER'), ('ML', 'MASALA')], default='PL', max_length=2),
        ),
    ]
