# Generated by Django 6.0.1 on 2026-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('PL', 'PLAIN'), ('EL', 'ELAICHI'), ('ML', 'MASALA'), ('KL', 'KIWI'), ('GR', 'GINGER')], default='PL', max_length=2),
        ),
    ]
